server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /index.html {
    add_header Cache-Control "no-store";
  }

  location ~* \.(?:js|css)$ {
    add_header Cache-Control "no-store";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /appUser/ {
    proxy_pass http://backend:8080/appUser/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /article/ {
    proxy_pass http://backend:8080/article/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /category/ {
    proxy_pass http://backend:8080/category/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
